services:
  postgresql:
    image: postgres:15
    container_name: my-postgres
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ftp-server:
    image: delfer/alpine-ftp-server
    container_name: ftp-server
    restart: always
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    environment:
      - USERS=myuser|mypassword|home/user/assets
      - ADDRESS=127.0.0.1
      - MIN_PORT=21000
      - MAX_PORT=21010
    volumes:
      - ftp_data:/home/user/assets

    

volumes:
  postgres_data:
  ftp_data:
  